"""Create letter table

Revision ID: 156374340d5d
Revises: 24382d85abe1
Create Date: 2025-05-10 11:10:03.570266

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "156374340d5d"
down_revision = "24382d85abe1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "file_generated_letter",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("letter_id", sa.Uuid(), nullable=False),
        sa.Column("resume_id", sa.Uuid(), nullable=False),
        sa.Column(
            "filename", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "file_extension",
            sqlmodel.sql.sqltypes.AutoString(length=10),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["resume_id"],
            ["file_resume.file_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("letter_id"),
    )
    op.create_index(
        op.f("ix_file_generated_letter_resume_id"),
        "file_generated_letter",
        ["resume_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_file_generated_letter_resume_id"), table_name="file_generated_letter"
    )
    op.drop_table("file_generated_letter")
    # ### end Alembic commands ###
